// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.27.0
// source: jumjump/v1/game.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cmd int32

const (
	Cmd_CMD_UNSPECIFIED   Cmd = 0
	Cmd_C2S_LOGIN         Cmd = 1001
	Cmd_S2C_LOGIN_ACK     Cmd = 1002
	Cmd_C2S_MATCH_START   Cmd = 1101
	Cmd_C2S_MATCH_CANCEL  Cmd = 1102
	Cmd_S2C_MATCH_FOUND   Cmd = 1103
	Cmd_S2C_GAME_START    Cmd = 1201
	Cmd_C2S_MOVE          Cmd = 1202
	Cmd_S2C_MOVE_RESULT   Cmd = 1203
	Cmd_S2C_TURN_CHANGE   Cmd = 1204
	Cmd_S2C_SNAPSHOT      Cmd = 1205
	Cmd_S2C_GAME_OVER     Cmd = 1206
	Cmd_C2S_PING          Cmd = 1301
	Cmd_S2C_PONG          Cmd = 1302
	Cmd_C2S_RECONNECT     Cmd = 1303
	Cmd_S2C_RECONNECT_ACK Cmd = 1304
	Cmd_S2C_ERROR         Cmd = 9001
)

// Enum value maps for Cmd.
var (
	Cmd_name = map[int32]string{
		0:    "CMD_UNSPECIFIED",
		1001: "C2S_LOGIN",
		1002: "S2C_LOGIN_ACK",
		1101: "C2S_MATCH_START",
		1102: "C2S_MATCH_CANCEL",
		1103: "S2C_MATCH_FOUND",
		1201: "S2C_GAME_START",
		1202: "C2S_MOVE",
		1203: "S2C_MOVE_RESULT",
		1204: "S2C_TURN_CHANGE",
		1205: "S2C_SNAPSHOT",
		1206: "S2C_GAME_OVER",
		1301: "C2S_PING",
		1302: "S2C_PONG",
		1303: "C2S_RECONNECT",
		1304: "S2C_RECONNECT_ACK",
		9001: "S2C_ERROR",
	}
	Cmd_value = map[string]int32{
		"CMD_UNSPECIFIED":   0,
		"C2S_LOGIN":         1001,
		"S2C_LOGIN_ACK":     1002,
		"C2S_MATCH_START":   1101,
		"C2S_MATCH_CANCEL":  1102,
		"S2C_MATCH_FOUND":   1103,
		"S2C_GAME_START":    1201,
		"C2S_MOVE":          1202,
		"S2C_MOVE_RESULT":   1203,
		"S2C_TURN_CHANGE":   1204,
		"S2C_SNAPSHOT":      1205,
		"S2C_GAME_OVER":     1206,
		"C2S_PING":          1301,
		"S2C_PONG":          1302,
		"C2S_RECONNECT":     1303,
		"S2C_RECONNECT_ACK": 1304,
		"S2C_ERROR":         9001,
	}
)

func (x Cmd) Enum() *Cmd {
	p := new(Cmd)
	*p = x
	return p
}

func (x Cmd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cmd) Descriptor() protoreflect.EnumDescriptor {
	return file_jumjump_v1_game_proto_enumTypes[0].Descriptor()
}

func (Cmd) Type() protoreflect.EnumType {
	return &file_jumjump_v1_game_proto_enumTypes[0]
}

func (x Cmd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cmd.Descriptor instead.
func (Cmd) EnumDescriptor() ([]byte, []int) {
	return file_jumjump_v1_game_proto_rawDescGZIP(), []int{0}
}

type Envelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd         uint32 `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Seq         uint64 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Ack         uint64 `protobuf:"varint,3,opt,name=ack,proto3" json:"ack,omitempty"`
	Ts          int64  `protobuf:"varint,4,opt,name=ts,proto3" json:"ts,omitempty"`
	Payload     []byte `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	RoomId      string `protobuf:"bytes,6,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomVersion uint32 `protobuf:"varint,7,opt,name=room_version,json=roomVersion,proto3" json:"room_version,omitempty"`
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumjump_v1_game_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_jumjump_v1_game_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_jumjump_v1_game_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetCmd() uint32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *Envelope) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Envelope) GetAck() uint64 {
	if x != nil {
		return x.Ack
	}
	return 0
}

func (x *Envelope) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Envelope) GetRoomVersion() uint32 {
	if x != nil {
		return x.RoomVersion
	}
	return 0
}

type LoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WxCode        string `protobuf:"bytes,1,opt,name=wx_code,json=wxCode,proto3" json:"wx_code,omitempty"`
	ClientVersion string `protobuf:"bytes,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumjump_v1_game_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_jumjump_v1_game_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_jumjump_v1_game_proto_rawDescGZIP(), []int{1}
}

func (x *LoginReq) GetWxCode() string {
	if x != nil {
		return x.WxCode
	}
	return ""
}

func (x *LoginReq) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

type LoginAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId        uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token         string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	TokenExpireAt int64  `protobuf:"varint,3,opt,name=token_expire_at,json=tokenExpireAt,proto3" json:"token_expire_at,omitempty"`
}

func (x *LoginAck) Reset() {
	*x = LoginAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumjump_v1_game_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginAck) ProtoMessage() {}

func (x *LoginAck) ProtoReflect() protoreflect.Message {
	mi := &file_jumjump_v1_game_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginAck.ProtoReflect.Descriptor instead.
func (*LoginAck) Descriptor() ([]byte, []int) {
	return file_jumjump_v1_game_proto_rawDescGZIP(), []int{2}
}

func (x *LoginAck) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginAck) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginAck) GetTokenExpireAt() int64 {
	if x != nil {
		return x.TokenExpireAt
	}
	return 0
}

type MatchStartReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode uint32 `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
}

func (x *MatchStartReq) Reset() {
	*x = MatchStartReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumjump_v1_game_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchStartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStartReq) ProtoMessage() {}

func (x *MatchStartReq) ProtoReflect() protoreflect.Message {
	mi := &file_jumjump_v1_game_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStartReq.ProtoReflect.Descriptor instead.
func (*MatchStartReq) Descriptor() ([]byte, []int) {
	return file_jumjump_v1_game_proto_rawDescGZIP(), []int{3}
}

func (x *MatchStartReq) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type MatchCancelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MatchCancelReq) Reset() {
	*x = MatchCancelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumjump_v1_game_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchCancelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCancelReq) ProtoMessage() {}

func (x *MatchCancelReq) ProtoReflect() protoreflect.Message {
	mi := &file_jumjump_v1_game_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCancelReq.ProtoReflect.Descriptor instead.
func (*MatchCancelReq) Descriptor() ([]byte, []int) {
	return file_jumjump_v1_game_proto_rawDescGZIP(), []int{4}
}

type MatchFound struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId         string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	SelfUserId     uint64 `protobuf:"varint,2,opt,name=self_user_id,json=selfUserId,proto3" json:"self_user_id,omitempty"`
	OpponentUserId uint64 `protobuf:"varint,3,opt,name=opponent_user_id,json=opponentUserId,proto3" json:"opponent_user_id,omitempty"`
	SelfSide       int32  `protobuf:"varint,4,opt,name=self_side,json=selfSide,proto3" json:"self_side,omitempty"`
}

func (x *MatchFound) Reset() {
	*x = MatchFound{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumjump_v1_game_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchFound) ProtoMessage() {}

func (x *MatchFound) ProtoReflect() protoreflect.Message {
	mi := &file_jumjump_v1_game_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchFound.ProtoReflect.Descriptor instead.
func (*MatchFound) Descriptor() ([]byte, []int) {
	return file_jumjump_v1_game_proto_rawDescGZIP(), []int{5}
}

func (x *MatchFound) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MatchFound) GetSelfUserId() uint64 {
	if x != nil {
		return x.SelfUserId
	}
	return 0
}

func (x *MatchFound) GetOpponentUserId() uint64 {
	if x != nil {
		return x.OpponentUserId
	}
	return 0
}

func (x *MatchFound) GetSelfSide() int32 {
	if x != nil {
		return x.SelfSide
	}
	return 0
}

type Pos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Pos) Reset() {
	*x = Pos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumjump_v1_game_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pos) ProtoMessage() {}

func (x *Pos) ProtoReflect() protoreflect.Message {
	mi := &file_jumjump_v1_game_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pos.ProtoReflect.Descriptor instead.
func (*Pos) Descriptor() ([]byte, []int) {
	return file_jumjump_v1_game_proto_rawDescGZIP(), []int{6}
}

func (x *Pos) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Pos) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Piece struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerId uint64 `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Pos     *Pos   `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`
}

func (x *Piece) Reset() {
	*x = Piece{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumjump_v1_game_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Piece) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Piece) ProtoMessage() {}

func (x *Piece) ProtoReflect() protoreflect.Message {
	mi := &file_jumjump_v1_game_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Piece.ProtoReflect.Descriptor instead.
func (*Piece) Descriptor() ([]byte, []int) {
	return file_jumjump_v1_game_proto_rawDescGZIP(), []int{7}
}

func (x *Piece) GetOwnerId() uint64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *Piece) GetPos() *Pos {
	if x != nil {
		return x.Pos
	}
	return nil
}

type GameStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId            string   `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Pieces            []*Piece `protobuf:"bytes,2,rep,name=pieces,proto3" json:"pieces,omitempty"`
	CurrentTurnUserId uint64   `protobuf:"varint,3,opt,name=current_turn_user_id,json=currentTurnUserId,proto3" json:"current_turn_user_id,omitempty"`
	TurnDeadlineMs    int64    `protobuf:"varint,4,opt,name=turn_deadline_ms,json=turnDeadlineMs,proto3" json:"turn_deadline_ms,omitempty"`
	RoomVersion       uint32   `protobuf:"varint,5,opt,name=room_version,json=roomVersion,proto3" json:"room_version,omitempty"`
}

func (x *GameStart) Reset() {
	*x = GameStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumjump_v1_game_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStart) ProtoMessage() {}

func (x *GameStart) ProtoReflect() protoreflect.Message {
	mi := &file_jumjump_v1_game_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStart.ProtoReflect.Descriptor instead.
func (*GameStart) Descriptor() ([]byte, []int) {
	return file_jumjump_v1_game_proto_rawDescGZIP(), []int{8}
}

func (x *GameStart) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GameStart) GetPieces() []*Piece {
	if x != nil {
		return x.Pieces
	}
	return nil
}

func (x *GameStart) GetCurrentTurnUserId() uint64 {
	if x != nil {
		return x.CurrentTurnUserId
	}
	return 0
}

func (x *GameStart) GetTurnDeadlineMs() int64 {
	if x != nil {
		return x.TurnDeadlineMs
	}
	return 0
}

func (x *GameStart) GetRoomVersion() uint32 {
	if x != nil {
		return x.RoomVersion
	}
	return 0
}

type MoveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From *Pos   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To   *Pos   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Path []*Pos `protobuf:"bytes,3,rep,name=path,proto3" json:"path,omitempty"`
}

func (x *MoveReq) Reset() {
	*x = MoveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumjump_v1_game_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveReq) ProtoMessage() {}

func (x *MoveReq) ProtoReflect() protoreflect.Message {
	mi := &file_jumjump_v1_game_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveReq.ProtoReflect.Descriptor instead.
func (*MoveReq) Descriptor() ([]byte, []int) {
	return file_jumjump_v1_game_proto_rawDescGZIP(), []int{9}
}

func (x *MoveReq) GetFrom() *Pos {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *MoveReq) GetTo() *Pos {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *MoveReq) GetPath() []*Pos {
	if x != nil {
		return x.Path
	}
	return nil
}

type MoveResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActorUserId  uint64 `protobuf:"varint,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	From         *Pos   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To           *Pos   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Accepted     bool   `protobuf:"varint,4,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectReason string `protobuf:"bytes,5,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	RoomVersion  uint32 `protobuf:"varint,6,opt,name=room_version,json=roomVersion,proto3" json:"room_version,omitempty"`
	Path         []*Pos `protobuf:"bytes,7,rep,name=path,proto3" json:"path,omitempty"`
}

func (x *MoveResult) Reset() {
	*x = MoveResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumjump_v1_game_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResult) ProtoMessage() {}

func (x *MoveResult) ProtoReflect() protoreflect.Message {
	mi := &file_jumjump_v1_game_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResult.ProtoReflect.Descriptor instead.
func (*MoveResult) Descriptor() ([]byte, []int) {
	return file_jumjump_v1_game_proto_rawDescGZIP(), []int{10}
}

func (x *MoveResult) GetActorUserId() uint64 {
	if x != nil {
		return x.ActorUserId
	}
	return 0
}

func (x *MoveResult) GetFrom() *Pos {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *MoveResult) GetTo() *Pos {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *MoveResult) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *MoveResult) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *MoveResult) GetRoomVersion() uint32 {
	if x != nil {
		return x.RoomVersion
	}
	return 0
}

func (x *MoveResult) GetPath() []*Pos {
	if x != nil {
		return x.Path
	}
	return nil
}

type TurnChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentTurnUserId uint64 `protobuf:"varint,1,opt,name=current_turn_user_id,json=currentTurnUserId,proto3" json:"current_turn_user_id,omitempty"`
	TurnDeadlineMs    int64  `protobuf:"varint,2,opt,name=turn_deadline_ms,json=turnDeadlineMs,proto3" json:"turn_deadline_ms,omitempty"`
	RoomVersion       uint32 `protobuf:"varint,3,opt,name=room_version,json=roomVersion,proto3" json:"room_version,omitempty"`
}

func (x *TurnChange) Reset() {
	*x = TurnChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumjump_v1_game_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TurnChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnChange) ProtoMessage() {}

func (x *TurnChange) ProtoReflect() protoreflect.Message {
	mi := &file_jumjump_v1_game_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnChange.ProtoReflect.Descriptor instead.
func (*TurnChange) Descriptor() ([]byte, []int) {
	return file_jumjump_v1_game_proto_rawDescGZIP(), []int{11}
}

func (x *TurnChange) GetCurrentTurnUserId() uint64 {
	if x != nil {
		return x.CurrentTurnUserId
	}
	return 0
}

func (x *TurnChange) GetTurnDeadlineMs() int64 {
	if x != nil {
		return x.TurnDeadlineMs
	}
	return 0
}

func (x *TurnChange) GetRoomVersion() uint32 {
	if x != nil {
		return x.RoomVersion
	}
	return 0
}

type Snapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId            string   `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Pieces            []*Piece `protobuf:"bytes,2,rep,name=pieces,proto3" json:"pieces,omitempty"`
	CurrentTurnUserId uint64   `protobuf:"varint,3,opt,name=current_turn_user_id,json=currentTurnUserId,proto3" json:"current_turn_user_id,omitempty"`
	TurnDeadlineMs    int64    `protobuf:"varint,4,opt,name=turn_deadline_ms,json=turnDeadlineMs,proto3" json:"turn_deadline_ms,omitempty"`
	RoomVersion       uint32   `protobuf:"varint,5,opt,name=room_version,json=roomVersion,proto3" json:"room_version,omitempty"`
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumjump_v1_game_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_jumjump_v1_game_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_jumjump_v1_game_proto_rawDescGZIP(), []int{12}
}

func (x *Snapshot) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Snapshot) GetPieces() []*Piece {
	if x != nil {
		return x.Pieces
	}
	return nil
}

func (x *Snapshot) GetCurrentTurnUserId() uint64 {
	if x != nil {
		return x.CurrentTurnUserId
	}
	return 0
}

func (x *Snapshot) GetTurnDeadlineMs() int64 {
	if x != nil {
		return x.TurnDeadlineMs
	}
	return 0
}

func (x *Snapshot) GetRoomVersion() uint32 {
	if x != nil {
		return x.RoomVersion
	}
	return 0
}

type GameOver struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId       string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	WinnerUserId uint64 `protobuf:"varint,2,opt,name=winner_user_id,json=winnerUserId,proto3" json:"winner_user_id,omitempty"`
	Reason       uint32 `protobuf:"varint,3,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *GameOver) Reset() {
	*x = GameOver{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumjump_v1_game_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameOver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameOver) ProtoMessage() {}

func (x *GameOver) ProtoReflect() protoreflect.Message {
	mi := &file_jumjump_v1_game_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameOver.ProtoReflect.Descriptor instead.
func (*GameOver) Descriptor() ([]byte, []int) {
	return file_jumjump_v1_game_proto_rawDescGZIP(), []int{13}
}

func (x *GameOver) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GameOver) GetWinnerUserId() uint64 {
	if x != nil {
		return x.WinnerUserId
	}
	return 0
}

func (x *GameOver) GetReason() uint32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

type Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientTs int64 `protobuf:"varint,1,opt,name=client_ts,json=clientTs,proto3" json:"client_ts,omitempty"`
}

func (x *Ping) Reset() {
	*x = Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumjump_v1_game_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_jumjump_v1_game_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_jumjump_v1_game_proto_rawDescGZIP(), []int{14}
}

func (x *Ping) GetClientTs() int64 {
	if x != nil {
		return x.ClientTs
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientTs int64 `protobuf:"varint,1,opt,name=client_ts,json=clientTs,proto3" json:"client_ts,omitempty"`
	ServerTs int64 `protobuf:"varint,2,opt,name=server_ts,json=serverTs,proto3" json:"server_ts,omitempty"`
}

func (x *Pong) Reset() {
	*x = Pong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumjump_v1_game_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_jumjump_v1_game_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_jumjump_v1_game_proto_rawDescGZIP(), []int{15}
}

func (x *Pong) GetClientTs() int64 {
	if x != nil {
		return x.ClientTs
	}
	return 0
}

func (x *Pong) GetServerTs() int64 {
	if x != nil {
		return x.ServerTs
	}
	return 0
}

type ReconnectReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token           string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RoomId          string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	LastRoomVersion uint32 `protobuf:"varint,3,opt,name=last_room_version,json=lastRoomVersion,proto3" json:"last_room_version,omitempty"`
}

func (x *ReconnectReq) Reset() {
	*x = ReconnectReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumjump_v1_game_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReconnectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnectReq) ProtoMessage() {}

func (x *ReconnectReq) ProtoReflect() protoreflect.Message {
	mi := &file_jumjump_v1_game_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconnectReq.ProtoReflect.Descriptor instead.
func (*ReconnectReq) Descriptor() ([]byte, []int) {
	return file_jumjump_v1_game_proto_rawDescGZIP(), []int{16}
}

func (x *ReconnectReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ReconnectReq) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ReconnectReq) GetLastRoomVersion() uint32 {
	if x != nil {
		return x.LastRoomVersion
	}
	return 0
}

type ReconnectAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok     bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *ReconnectAck) Reset() {
	*x = ReconnectAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumjump_v1_game_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReconnectAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnectAck) ProtoMessage() {}

func (x *ReconnectAck) ProtoReflect() protoreflect.Message {
	mi := &file_jumjump_v1_game_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconnectAck.ProtoReflect.Descriptor instead.
func (*ReconnectAck) Descriptor() ([]byte, []int) {
	return file_jumjump_v1_game_proto_rawDescGZIP(), []int{17}
}

func (x *ReconnectAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ReconnectAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ErrorMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ErrorMsg) Reset() {
	*x = ErrorMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jumjump_v1_game_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMsg) ProtoMessage() {}

func (x *ErrorMsg) ProtoReflect() protoreflect.Message {
	mi := &file_jumjump_v1_game_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMsg.ProtoReflect.Descriptor instead.
func (*ErrorMsg) Descriptor() ([]byte, []int) {
	return file_jumjump_v1_game_proto_rawDescGZIP(), []int{18}
}

func (x *ErrorMsg) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorMsg) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_jumjump_v1_game_proto protoreflect.FileDescriptor

var file_jumjump_v1_game_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6a, 0x75, 0x6d, 0x6a, 0x75, 0x6d, 0x70, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6a, 0x75, 0x6d, 0x6a, 0x75, 0x6d, 0x70,
	0x2e, 0x76, 0x31, 0x22, 0xa6, 0x01, 0x0a, 0x08, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x63,
	0x6d, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x03, 0x73, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x6f, 0x6f,
	0x6d, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0b, 0x72, 0x6f, 0x6f, 0x6d, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x4a, 0x0a, 0x08,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x77, 0x78, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x77, 0x78, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x61, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x41, 0x63, 0x6b, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x26, 0x0a, 0x0f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x65, 0x78, 0x70,
	0x69, 0x72, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x41, 0x74, 0x22, 0x23, 0x0a, 0x0d, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04,
	0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65,
	0x22, 0x10, 0x0a, 0x0e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52,
	0x65, 0x71, 0x22, 0x8e, 0x01, 0x0a, 0x0a, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x46, 0x6f, 0x75, 0x6e,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x73, 0x65,
	0x6c, 0x66, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0a, 0x73, 0x65, 0x6c, 0x66, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10,
	0x6f, 0x70, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x6f, 0x70, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6c, 0x66, 0x5f, 0x73,
	0x69, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x66, 0x53,
	0x69, 0x64, 0x65, 0x22, 0x21, 0x0a, 0x03, 0x50, 0x6f, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x22, 0x45, 0x0a, 0x05, 0x50, 0x69, 0x65, 0x63, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x03, 0x70, 0x6f,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6a, 0x75, 0x6d, 0x6a, 0x75, 0x6d,
	0x70, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x73, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x22, 0xcd, 0x01,
	0x0a, 0x09, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72,
	0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x06, 0x70, 0x69, 0x65, 0x63, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6a, 0x75, 0x6d, 0x6a, 0x75, 0x6d, 0x70, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x69, 0x65, 0x63, 0x65, 0x52, 0x06, 0x70, 0x69, 0x65, 0x63, 0x65, 0x73, 0x12,
	0x2f, 0x0a, 0x14, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x75, 0x72, 0x6e, 0x5f,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x11, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x54, 0x75, 0x72, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x28, 0x0a, 0x10, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e,
	0x65, 0x5f, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x74, 0x75, 0x72, 0x6e,
	0x44, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x4d, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x6f,
	0x6f, 0x6d, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0b, 0x72, 0x6f, 0x6f, 0x6d, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x74, 0x0a,
	0x07, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x12, 0x23, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6a, 0x75, 0x6d, 0x6a, 0x75, 0x6d, 0x70,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x73, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x1f, 0x0a,
	0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6a, 0x75, 0x6d, 0x6a,
	0x75, 0x6d, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x73, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x23,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6a,
	0x75, 0x6d, 0x6a, 0x75, 0x6d, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x73, 0x52, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x22, 0xff, 0x01, 0x0a, 0x0a, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x22, 0x0a, 0x0d, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6a, 0x75, 0x6d, 0x6a, 0x75, 0x6d, 0x70, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x6f, 0x73, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x1f, 0x0a, 0x02, 0x74,
	0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6a, 0x75, 0x6d, 0x6a, 0x75, 0x6d,
	0x70, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x73, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x1a, 0x0a, 0x08,
	0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x6a, 0x65,
	0x63, 0x74, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x21, 0x0a,
	0x0c, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0b, 0x72, 0x6f, 0x6f, 0x6d, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x23, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x6a, 0x75, 0x6d, 0x6a, 0x75, 0x6d, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x73, 0x52,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x8a, 0x01, 0x0a, 0x0a, 0x54, 0x75, 0x72, 0x6e, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x12, 0x2f, 0x0a, 0x14, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f,
	0x74, 0x75, 0x72, 0x6e, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x11, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x54, 0x75, 0x72, 0x6e, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x64, 0x65,
	0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0e, 0x74, 0x75, 0x72, 0x6e, 0x44, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x4d, 0x73, 0x12,
	0x21, 0x0a, 0x0c, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x72, 0x6f, 0x6f, 0x6d, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0xcc, 0x01, 0x0a, 0x08, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x06, 0x70, 0x69, 0x65, 0x63,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6a, 0x75, 0x6d, 0x6a, 0x75,
	0x6d, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69, 0x65, 0x63, 0x65, 0x52, 0x06, 0x70, 0x69, 0x65,
	0x63, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x14, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x74,
	0x75, 0x72, 0x6e, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x11, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x54, 0x75, 0x72, 0x6e, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x64, 0x65, 0x61,
	0x64, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e,
	0x74, 0x75, 0x72, 0x6e, 0x44, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x4d, 0x73, 0x12, 0x21,
	0x0a, 0x0c, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x72, 0x6f, 0x6f, 0x6d, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x22, 0x61, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x12, 0x17, 0x0a,
	0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72,
	0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c,
	0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x22, 0x23, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x1b, 0x0a, 0x09,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x73, 0x22, 0x40, 0x0a, 0x04, 0x50, 0x6f, 0x6e,
	0x67, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x73, 0x12, 0x1b,
	0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x73, 0x22, 0x69, 0x0a, 0x0c, 0x52,
	0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x6c, 0x61,
	0x73, 0x74, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x36, 0x0a, 0x0c, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x41, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x38,
	0x0a, 0x08, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0xd2, 0x02, 0x0a, 0x03, 0x43, 0x6d, 0x64,
	0x12, 0x13, 0x0a, 0x0f, 0x43, 0x4d, 0x44, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x09, 0x43, 0x32, 0x53, 0x5f, 0x4c, 0x4f, 0x47,
	0x49, 0x4e, 0x10, 0xe9, 0x07, 0x12, 0x12, 0x0a, 0x0d, 0x53, 0x32, 0x43, 0x5f, 0x4c, 0x4f, 0x47,
	0x49, 0x4e, 0x5f, 0x41, 0x43, 0x4b, 0x10, 0xea, 0x07, 0x12, 0x14, 0x0a, 0x0f, 0x43, 0x32, 0x53,
	0x5f, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0xcd, 0x08, 0x12,
	0x15, 0x0a, 0x10, 0x43, 0x32, 0x53, 0x5f, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x5f, 0x43, 0x41, 0x4e,
	0x43, 0x45, 0x4c, 0x10, 0xce, 0x08, 0x12, 0x14, 0x0a, 0x0f, 0x53, 0x32, 0x43, 0x5f, 0x4d, 0x41,
	0x54, 0x43, 0x48, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0xcf, 0x08, 0x12, 0x13, 0x0a, 0x0e,
	0x53, 0x32, 0x43, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0xb1,
	0x09, 0x12, 0x0d, 0x0a, 0x08, 0x43, 0x32, 0x53, 0x5f, 0x4d, 0x4f, 0x56, 0x45, 0x10, 0xb2, 0x09,
	0x12, 0x14, 0x0a, 0x0f, 0x53, 0x32, 0x43, 0x5f, 0x4d, 0x4f, 0x56, 0x45, 0x5f, 0x52, 0x45, 0x53,
	0x55, 0x4c, 0x54, 0x10, 0xb3, 0x09, 0x12, 0x14, 0x0a, 0x0f, 0x53, 0x32, 0x43, 0x5f, 0x54, 0x55,
	0x52, 0x4e, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x10, 0xb4, 0x09, 0x12, 0x11, 0x0a, 0x0c,
	0x53, 0x32, 0x43, 0x5f, 0x53, 0x4e, 0x41, 0x50, 0x53, 0x48, 0x4f, 0x54, 0x10, 0xb5, 0x09, 0x12,
	0x12, 0x0a, 0x0d, 0x53, 0x32, 0x43, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x4f, 0x56, 0x45, 0x52,
	0x10, 0xb6, 0x09, 0x12, 0x0d, 0x0a, 0x08, 0x43, 0x32, 0x53, 0x5f, 0x50, 0x49, 0x4e, 0x47, 0x10,
	0x95, 0x0a, 0x12, 0x0d, 0x0a, 0x08, 0x53, 0x32, 0x43, 0x5f, 0x50, 0x4f, 0x4e, 0x47, 0x10, 0x96,
	0x0a, 0x12, 0x12, 0x0a, 0x0d, 0x43, 0x32, 0x53, 0x5f, 0x52, 0x45, 0x43, 0x4f, 0x4e, 0x4e, 0x45,
	0x43, 0x54, 0x10, 0x97, 0x0a, 0x12, 0x16, 0x0a, 0x11, 0x53, 0x32, 0x43, 0x5f, 0x52, 0x45, 0x43,
	0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x5f, 0x41, 0x43, 0x4b, 0x10, 0x98, 0x0a, 0x12, 0x0e, 0x0a,
	0x09, 0x53, 0x32, 0x43, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0xa9, 0x46, 0x42, 0x2f, 0x5a,
	0x1d, 0x6a, 0x75, 0x6d, 0x6a, 0x75, 0x6d, 0x70, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0xaa, 0x02,
	0x0d, 0x4a, 0x75, 0x6d, 0x4a, 0x75, 0x6d, 0x70, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_jumjump_v1_game_proto_rawDescOnce sync.Once
	file_jumjump_v1_game_proto_rawDescData = file_jumjump_v1_game_proto_rawDesc
)

func file_jumjump_v1_game_proto_rawDescGZIP() []byte {
	file_jumjump_v1_game_proto_rawDescOnce.Do(func() {
		file_jumjump_v1_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_jumjump_v1_game_proto_rawDescData)
	})
	return file_jumjump_v1_game_proto_rawDescData
}

var file_jumjump_v1_game_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_jumjump_v1_game_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_jumjump_v1_game_proto_goTypes = []interface{}{
	(Cmd)(0),               // 0: jumjump.v1.Cmd
	(*Envelope)(nil),       // 1: jumjump.v1.Envelope
	(*LoginReq)(nil),       // 2: jumjump.v1.LoginReq
	(*LoginAck)(nil),       // 3: jumjump.v1.LoginAck
	(*MatchStartReq)(nil),  // 4: jumjump.v1.MatchStartReq
	(*MatchCancelReq)(nil), // 5: jumjump.v1.MatchCancelReq
	(*MatchFound)(nil),     // 6: jumjump.v1.MatchFound
	(*Pos)(nil),            // 7: jumjump.v1.Pos
	(*Piece)(nil),          // 8: jumjump.v1.Piece
	(*GameStart)(nil),      // 9: jumjump.v1.GameStart
	(*MoveReq)(nil),        // 10: jumjump.v1.MoveReq
	(*MoveResult)(nil),     // 11: jumjump.v1.MoveResult
	(*TurnChange)(nil),     // 12: jumjump.v1.TurnChange
	(*Snapshot)(nil),       // 13: jumjump.v1.Snapshot
	(*GameOver)(nil),       // 14: jumjump.v1.GameOver
	(*Ping)(nil),           // 15: jumjump.v1.Ping
	(*Pong)(nil),           // 16: jumjump.v1.Pong
	(*ReconnectReq)(nil),   // 17: jumjump.v1.ReconnectReq
	(*ReconnectAck)(nil),   // 18: jumjump.v1.ReconnectAck
	(*ErrorMsg)(nil),       // 19: jumjump.v1.ErrorMsg
}
var file_jumjump_v1_game_proto_depIdxs = []int32{
	7, // 0: jumjump.v1.Piece.pos:type_name -> jumjump.v1.Pos
	8, // 1: jumjump.v1.GameStart.pieces:type_name -> jumjump.v1.Piece
	7, // 2: jumjump.v1.MoveReq.from:type_name -> jumjump.v1.Pos
	7, // 3: jumjump.v1.MoveReq.to:type_name -> jumjump.v1.Pos
	7, // 4: jumjump.v1.MoveReq.path:type_name -> jumjump.v1.Pos
	7, // 5: jumjump.v1.MoveResult.from:type_name -> jumjump.v1.Pos
	7, // 6: jumjump.v1.MoveResult.to:type_name -> jumjump.v1.Pos
	7, // 7: jumjump.v1.MoveResult.path:type_name -> jumjump.v1.Pos
	8, // 8: jumjump.v1.Snapshot.pieces:type_name -> jumjump.v1.Piece
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_jumjump_v1_game_proto_init() }
func file_jumjump_v1_game_proto_init() {
	if File_jumjump_v1_game_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jumjump_v1_game_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Envelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumjump_v1_game_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumjump_v1_game_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumjump_v1_game_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchStartReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumjump_v1_game_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchCancelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumjump_v1_game_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchFound); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumjump_v1_game_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumjump_v1_game_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Piece); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumjump_v1_game_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumjump_v1_game_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumjump_v1_game_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumjump_v1_game_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TurnChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumjump_v1_game_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Snapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumjump_v1_game_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameOver); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumjump_v1_game_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumjump_v1_game_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumjump_v1_game_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReconnectReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumjump_v1_game_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReconnectAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jumjump_v1_game_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jumjump_v1_game_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jumjump_v1_game_proto_goTypes,
		DependencyIndexes: file_jumjump_v1_game_proto_depIdxs,
		EnumInfos:         file_jumjump_v1_game_proto_enumTypes,
		MessageInfos:      file_jumjump_v1_game_proto_msgTypes,
	}.Build()
	File_jumjump_v1_game_proto = out.File
	file_jumjump_v1_game_proto_rawDesc = nil
	file_jumjump_v1_game_proto_goTypes = nil
	file_jumjump_v1_game_proto_depIdxs = nil
}
